services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - appnet

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet

networks:
  appnet:
